config:
  common:
    baseUri: "JIRA BASE URI"
    userId: "UserId"
    password: "Password"
    sprintFieldName: "customfield_10104"
  particular:
    projectKey: "REVRSLTS"
    boardId: "2"
    issueTypeId: "10001"
    summary: "Review: "
